raxml_command   = config["parameters"]["raxml-ng"]["command"]
iqtree_command   = config["parameters"]["iqtree"]["command"]

num_pars_trees = config["parameters"]["num_pars_trees"]
num_rand_trees = config["parameters"]["num_rand_trees"]
pars_seeds = list(range(num_pars_trees))
rand_seeds = list(range(num_pars_trees, num_pars_trees + num_rand_trees))

lheps_opts = config["parameters"]["lh_eps"]
lheps_trip_opts = config["parameters"]["lh_eps_trip"]

base_dir = config["data"]["outdir"]
base_dir_raxml = base_dir + "raxml/"
base_name_raxml = "lh{lheps}_lbt{lheps_trip}"

full_dir_raxml = base_dir_raxml + base_name_raxml + "/"

base_name_pars  = "pars_s{seed}_"
base_name_rand  = "rand_s{seed}_"

full_file_path_raxml = full_dir_raxml + base_name_raxml

file_name_raxml_pars        = base_name_pars + base_name_raxml
full_dir_raxml_pars         = full_dir_raxml + "pT/"
full_file_path_raxml_pars   = full_dir_raxml_pars  + file_name_raxml_pars

file_name_raxml_rand        = base_name_rand + base_name_raxml
full_dir_raxml_rand         = full_dir_raxml + "rT/"
full_file_path_raxml_rand   = full_dir_raxml_rand + file_name_raxml_rand

file_name_raxml_eval_pars       = "E_" + file_name_raxml_pars
file_name_raxml_eval_rand       = "E_" + file_name_raxml_rand

full_dir_raxml_eval_pars        = full_dir_raxml + "EpT/"
full_dir_raxml_eval_rand        = full_dir_raxml + "ErT/"
full_file_path_raxml_eval_pars  = full_dir_raxml_eval_pars + file_name_raxml_eval_pars
full_file_path_raxml_eval_rand  = full_dir_raxml_eval_rand + file_name_raxml_eval_rand

full_dir_raxml_eval_pars_start          = full_dir_raxml + "EpST/"
full_dir_raxml_eval_rand_start          = full_dir_raxml + "ErST/"
full_file_path_raxml_eval_pars_start    = full_dir_raxml_eval_pars_start + file_name_raxml_eval_pars
full_file_path_raxml_eval_rand_start    = full_dir_raxml_eval_rand_start + file_name_raxml_eval_rand

rule raxml_database:
    input:
        database = f"{base_dir}raxml_results.sqlite3", 
        

rule save_raxml_settings_in_file:
    output:
        params = f"{full_dir_raxml}parameters.json"
    params:
        num_pars_trees  = config["parameters"]["num_pars_trees"],
        num_rand_trees  = config["parameters"]["num_rand_trees"],
    run:
        import json
        data = {}
        data["lheps_auto"] = wildcards.lheps
        data["lheps_fast"] = wildcards.lheps
        data["lheps_slow"] = wildcards.lheps
        data["lheps_full"] = wildcards.lheps
        data["lheps_trip"] = wildcards.lheps_trip

        data["num_pars_trees"] = params.num_pars_trees
        data["num_rand_trees"] = params.num_rand_trees
        with open(output.params, 'w') as f:
            json.dump(data, f)



include: "rules/raxml_treesearch.smk"
include: "rules/raxml_collect_data.smk"
include: "rules/raxml_best_tree.smk"
include: "rules/raxml_evaluation.smk"
include: "rules/raxml_iqtree_statstests.smk"
include: "rules/save_raxml_results_to_database.smk"