raxml_command   = config["parameters"]["raxml-ng"]["command"]
iqtree_command   = config["parameters"]["iqtree"]["command"]

blmin_opts      = config["parameters"]["blmin"]
blmax_opts      = config["parameters"]["blmax"]
lh_eps_opts     = config["parameters"]["lh_eps"]
model_param_epsilon_opts    = config["parameters"]["model_epsilon"]
raxml_brlen_smoothings_opts = config["parameters"]["branch_length_smoothing"]
spr_lh_eps_opts         = config["parameters"]["spr_lh_epsilon"]
bfgs_fac_opts            = config["parameters"]["bfgs_factor"]

blmin_eval = float(config["parameters"]["eval"]["blmin"])
blmax_eval = float(config["parameters"]["eval"]["blmax"])
lh_eps_eval = float(config["parameters"]["eval"]["lh_eps"])
model_param_epsilon_eval    = float(config["parameters"]["eval"]["model_epsilon"])
raxml_brlen_smoothings_eval = float(config["parameters"]["eval"]["branch_length_smoothing"])
bfgs_fac_eval         = float(config["parameters"]["eval"]["bfgs_factor"])


num_pars_trees = config["parameters"]["num_pars_trees"]
num_rand_trees = config["parameters"]["num_rand_trees"]
pars_seeds = list(range(num_pars_trees))
rand_seeds = list(range(num_pars_trees, num_pars_trees + num_rand_trees))

base_dir = config["data"]["outdir"]
base_dir_raxml = base_dir + "raxml/"
base_name_raxml = "bi{blmin}_ba{blmax}_le{lh_eps}_re{model_epsilon}_bls{raxml_brlen_smoothings}_sprle{spr_lh_eps}_bfgs{bfgs_fac}"
full_dir_raxml = base_dir_raxml + base_name_raxml + "/"

base_name_pars  = "pars_s{seed}_"
base_name_rand  = "rand_s{seed}_"

full_file_path_raxml = full_dir_raxml + base_name_raxml

file_name_raxml_pars        = base_name_pars + base_name_raxml
full_dir_raxml_pars         = full_dir_raxml + "pT/"
full_file_path_raxml_pars   = full_dir_raxml_pars  + file_name_raxml_pars

file_name_raxml_rand        = base_name_rand + base_name_raxml
full_dir_raxml_rand         = full_dir_raxml + "rT/"
full_file_path_raxml_rand   = full_dir_raxml_rand + file_name_raxml_rand

file_name_raxml_eval_pars       = "E_" + file_name_raxml_pars
file_name_raxml_eval_rand       = "E_" + file_name_raxml_rand
full_dir_raxml_eval_pars        = full_dir_raxml + "EpT/"
full_dir_raxml_eval_rand        = full_dir_raxml + "ErT/"
full_file_path_raxml_eval_pars  = full_dir_raxml_eval_pars + file_name_raxml_eval_pars
full_file_path_raxml_eval_rand  = full_dir_raxml_eval_rand + file_name_raxml_eval_rand

rule raxml_database:
    input:
        database = f"{base_dir}raxml_results.sqlite3", 
        

rule save_raxml_settings_in_file:
    output:
        params = f"{full_dir_raxml}parameters.json"
    params:
        num_pars_trees  = config["parameters"]["num_pars_trees"],
        num_rand_trees  = config["parameters"]["num_rand_trees"],
    run:
        import json
        data = {}
        data["blmin"] = wildcards.blmin
        data["blmax"] = wildcards.blmax
        data["lh_eps"] = wildcards.lh_eps
        data["model_epsilon"] = wildcards.model_epsilon
        data["raxml_brlen_smoothings"] = wildcards.raxml_brlen_smoothings
        data["spr_lh_epsilon"] = wildcards.spr_lh_eps
        data["bfgs_factor"] = wildcards.bfgs_fac

        data["num_pars_trees"] = params.num_pars_trees
        data["num_rand_trees"] = params.num_rand_trees
        with open(output.params, 'w') as f:
            json.dump(data, f)



include: "rules/raxml_treesearch.smk"
include: "rules/raxml_collect_data.smk"
include: "rules/raxml_best_tree.smk"
include: "rules/raxml_evaluation.smk"
include: "rules/raxml_iqtree_statstests.smk"
include: "rules/save_raxml_results_to_database.smk"