raxml_command   = config["parameters"]["raxml-ng"]["command"]
iqtree_command   = config["parameters"]["iqtree"]["command"]

blmin_opts      = config["parameters"]["blmin"]
blmax_opts      = config["parameters"]["blmax"]
lh_eps_opts     = config["parameters"]["lh_eps"]
raxml_param_epsilon_opts    = config["parameters"]["raxml_param_epsilon"]
raxml_brlen_smoothings_opts = config["parameters"]["branch_length_smoothing"]

blmin_eval_opts = config["parameters"]["eval"]["blmin"]
blmax_eval_opts = config["parameters"]["eval"]["blmax"]
lh_eps_eval_opts = config["parameters"]["eval"]["lh_eps"]
raxml_param_epsilon_eval_opts    = config["parameters"]["eval"]["raxml_param_epsilon"]
raxml_brlen_smoothings_eval_opts = config["parameters"]["eval"]["branch_length_smoothing"]

num_pars_trees = config["parameters"]["num_pars_trees"]
num_rand_trees = config["parameters"]["num_rand_trees"]
pars_seeds = list(range(num_pars_trees))
rand_seeds = list(range(num_pars_trees, num_pars_trees + num_rand_trees))

base_dir = config["data"]["outdir"]
base_dir_raxml = base_dir + "raxml/"
base_name_raxml = "bi{blmin}_ba{blmax}_le{lh_eps}_re{raxml_param_epsilon}_bls{raxml_brlen_smoothings}"
full_dir_raxml = base_dir_raxml + base_name_raxml + "/"

base_name_pars  = "pars_s{seed}_"
base_name_rand  = "rand_s{seed}_"

full_file_path_raxml = full_dir_raxml + base_name_raxml

file_name_raxml_pars        = base_name_pars + base_name_raxml
full_dir_raxml_pars         = full_dir_raxml + "pT/"
full_file_path_raxml_pars   = full_dir_raxml_pars  + file_name_raxml_pars

file_name_raxml_rand        = base_name_rand + base_name_raxml
full_dir_raxml_rand         = full_dir_raxml + "rT/"
full_file_path_raxml_rand   = full_dir_raxml_rand + file_name_raxml_rand

base_name_raxml_eval        = "E_bi{blmin_eval}_ba{blmax_eval}_le{lh_eps_eval}_re{raxml_param_epsilon_eval}_bls{raxml_brlen_smoothings_eval}"
file_name_raxml_eval        = base_name_raxml_eval + "_S_" + base_name_raxml
full_dir_raxml_eval         = full_dir_raxml + "e/"
full_file_path_raxml_eval   = full_dir_raxml_eval + file_name_raxml_eval

rule raxml_database:
    input:
        database = f"{base_dir}raxml_results.sqlite3", 
        

rule save_raxml_settings_in_file:
    output:
        params = f"{full_dir_raxml}parameters.json"
    params:
        num_pars_trees  = config["parameters"]["num_pars_trees"],
        num_rand_trees  = config["parameters"]["num_rand_trees"],
    run:
        import json
        data = {}
        data["blmin"] = wildcards.blmin
        data["blmax"] = wildcards.blmax
        data["lh_eps"] = wildcards.lh_eps
        data["raxml_param_epsilon"] = wildcards.raxml_param_epsilon
        data["raxml_brlen_smoothings"] = wildcards.raxml_brlen_smoothings
        data["num_pars_trees"] = params.num_pars_trees
        data["num_rand_trees"] = params.num_rand_trees
        with open(output.params, 'w') as f:
            json.dump(data, f)



include: "rules/raxml_treesearch.smk"
include: "rules/raxml_collect_data.smk"
include: "rules/raxml_best_tree.smk"
include: "rules/raxml_evaluation.smk"
include: "rules/raxml_rfdistance.smk"
include: "rules/raxml_iqtree_statstests.smk"
include: "rules/save_raxml_results_to_database.smk"