data:
  #input: data/cluster_results/cascade/covid_data/fmsan/data/covid_edited.fasta
  #outdir: data/cluster_results/cascade/covid_data/fmsan/results_4Feb21
  #input: /Users/julia/Desktop/Masterarbeit/test-Datasets/DNA-Data/354/354.phy
  #outdir: data/cluster_results/ml/354/results
  input: /Users/julia/Desktop/Masterarbeit/MasterThesis/snakemake/data/ng-tutorial/prim.phy
  outdir: /Users/julia/Desktop/Masterarbeit/MasterThesis/snakemake/data/ng-tutorial/results/
  #input: data/covid_data/fmsan/data/covid_edited.fasta
  #outdir: data/covid_data/fmsan/results

parameters:
  # general parameter settings
  num_pars_trees: 4
  num_rand_trees: 0
  blmin: [1e-7, 1e-8, 1e-9, 1e-10]
  blmax: [100]
  lh_eps: [0.01]
  raxml_param_epsilon: [0.001]
  branch_length_smoothing: [32]

  eval:
    blmin: [1e-10]
    blmax: [100]
    lh_eps: [0.001]
    raxml_param_epsilon: [0.001]
    branch_length_smoothing: [64]

  # if you change the model: make sure to change both raxml and iqtree to the respective model
  model:
    raxml-ng: GTR+G
    iqtree: GTR+FO+G4
    fasttree: gtr

  # iqtree specific settings
  iqtree:
    command: iqtree
    threads: 2

  # raxml-ng specific settings
  raxml-ng:
    command: /Users/julia/Desktop/Masterarbeit/Masterthesis/snakemake/software/param-raxml-ng/bin/raxml-ng
    threads: 2

  fasttree:
    command: ./software/fasttree/ParamFastTree