data:
  input: /home/schmidja/MasterThesis/test-Datasets/DNA-Data/1604/1604.phy
  outdir: /hits/basement/cme/schmidja/MasterThesis/data/1604/results_22Mar21/
  
parameters:
  # general parameter settings
  num_pars_trees: 5
  num_rand_trees: 0
  blmin: [1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10]
  blmax: [10, 100]
  lh_eps: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
  raxml_param_epsilon: [0.001, 0.01, 0.1]
  branch_length_smoothing: [16, 32, 64]

  eval:
    blmin: [1e-10]
    blmax: [100]
    lh_eps: [0.001]
    raxml_param_epsilon: [0.001]
    branch_length_smoothing: [64]

  # if you change the model: make sure to change both raxml and iqtree to the respective model
  model:
    raxml-ng: GTR+G
    iqtree: GTR+FO+G4
    fasttree: gtr

  # iqtree specific settings
  iqtree:
    command: iqtree
    threads: 2

  # raxml-ng specific settings
  raxml-ng:
    command: ./software/param-raxml-ng/bin/raxml-ng
    threads: 2

  fasttree:
    command: ./software/fasttree/ParamFastTree