data:
  input: /Users/julia/Desktop/Masterarbeit/Datasets/BioinfProtocols/dataset/027.phy
  outdir: results/027/iqtree/

parameters:
  # general parameter settings
  num_pars_trees: 1
  num_rand_trees: 1

  lh_eps: [0.01, 0.1,] # 1, 10, 100, 1000]

  eval:
    # keep default values here as well
    lh_eps: 0.1

  # if you change the model: make sure to change all models
  model:
    raxml-ng: GTR+G
    iqtree: GTR+G4+FO
    fasttree: gtr

  # iqtree specific settings
  iqtree:
    command:  /Users/julia/Desktop/promotion/software/iqtree-2.1.3-MacOSX/bin/iqtree2
    threads: 2

  # raxml-ng specific settings
  raxml-ng:
    command: /Users/julia/Desktop/Promotion/software/raxml-ng/bin/raxml-ng
    threads: 2

  fasttree:
    command: ./software/fasttree/ParamFastTree