iqtree_command = config["parameters"]["iqtree"]["command"]

blmin_opts      = config["parameters"]["blmin"]
blmax_opts      = config["parameters"]["blmax"]
lh_eps_opts     = config["parameters"]["lh_eps"]

blmin_eval_opts = config["parameters"]["eval"]["blmin"]
blmax_eval_opts = config["parameters"]["eval"]["blmax"]
lh_eps_eval_opts = config["parameters"]["eval"]["lh_eps"]

num_pars_trees  = config["parameters"]["num_pars_trees"]
pars_seeds      = list(range(num_pars_trees))

base_dir            = config["data"]["outdir"]
base_dir_iqtree     = base_dir + "iqtree/"
base_name_iqtree    = "bi{blmin}_ba{blmax}_le{lh_eps}"
full_dir_iqtree     = base_dir_iqtree + base_name_iqtree + "/"

base_name_pars  = "pars_s{seed}_"

full_file_path_iqtree = full_dir_iqtree + base_name_iqtree

file_name_iqtree_pars = base_name_pars + base_name_iqtree

full_dir_iqtree_pars        = full_dir_iqtree + "pT/"
full_file_path_iqtree_pars  = full_dir_iqtree_pars + file_name_iqtree_pars

full_dir_iqtree_pars_tmp        = full_dir_iqtree_pars + "tmp/"
full_file_path_iqtree_pars_tmp  = full_dir_iqtree_pars_tmp + file_name_iqtree_pars

base_name_iqtree_eval = "E_bi{blmin_eval}_ba{blmax_eval}_le{lh_eps_eval}"
file_name_iqtree_eval = base_name_iqtree_eval + "_S_" + base_name_iqtree

full_dir_iqtree_eval        = full_dir_iqtree + "e/"
full_file_path_iqtree_eval  = full_dir_iqtree_eval + file_name_iqtree_eval

full_dir_iqtree_eval_tmp        = full_dir_iqtree_eval + "tmp/"
full_file_path_iqtree_eval_tmp  = full_dir_iqtree_eval_tmp + file_name_iqtree_eval

rule iqtree_database:
    input:
        database = f"{base_dir}iqtree_results.sqlite3"

rule save_iqtree_settings_in_file:
    output:
        params = f"{full_dir_iqtree}parameters.json"
    params:
        num_pars_trees  = config["parameters"]["num_pars_trees"],
    run:
        import json
        data = {}
        data["blmin"] = wildcards.blmin
        data["blmax"] = wildcards.blmax
        data["lh_eps"] = wildcards.lh_eps
        data["num_pars_trees"] = params.num_pars_trees
        with open(output.params, 'w') as f:
            json.dump(data, f)

include: "rules/iqtree_treesearch.smk"
include: "rules/iqtree_collect_data.smk"
include: "rules/iqtree_best_tree.smk"
include: "rules/iqtree_evaluation.smk"
include: "rules/iqtree_iqtree_statstests.smk"
include: "rules/save_iqtree_results_to_database.smk"